#####################################
# dataset SPECIFIC parameters: START
#####################################

download_datasets: 0  # If 1, and a valid URL is provided (see next parameter) then datasets will be downloaded automatically
                      # If 0, then datasets should be downloaded manually and placed in the datasets folder
dataset_urls:
  - 

train_test_sep: 1   # If train_test_sep is 1, then test_dataset and test_filepath should be defined
                      # If train_test_sep is 0, then train and test datasets will be combined

dataset: 'Wu2021_Breast'    # Name of the dataset
filepath: './datasets/Data_Wu2021_Breast_annotated_with_cell_types.parquet'  # Path to the dataset
                        
test_dataset: 'Qian2020_Breast'    # Name of the dataset 
test_filepath: './datasets/Data_Qian2020_Breast_annotated_with_cell_types.parquet'  # Path to the dataset


expr_with_housekeeping_genes: False    # Whether to perform experiment with housekeeping genes in the expression data
expr_with_highly_variable_genes: True    # Whether to perform experiment with highly variable genes in the expression data

opt_model: 0
remove_cols: False  # If number of features are more than 20,000 - set it to true

annotate_paper_results: 0  # If 1, then paper, x_from_paper and y_from_paper should be defined.
# paper: "Lall (2020)"      # The name of the paper from which the results are taken
# x_from_paper: 35          # No of selected features
# y_from_paper: .86         # Accuracy with selected features, with decimal point not percentage

###################################
# dataset SPECIFIC parameters: END
###################################




########################################
# COMMON parameters for datasets: START
########################################

target: 'type'
# target: 'Diagnosis'  # The target column in the dataset

model_name: "RF"

random_state: 42
debug: 0

num_runs: 20  

plot_acc: 1
plot_auc: 1

interactive: 0
shuffle_cols: 0

feature_ticks_ranges:
  # - [1, 11, 1]
  # - [11, 21, 1]
  # - [21, 31, 1]
  - [1, 51, 1]
  - [60, 201, 10]
  - [300, 2001, 100]

######################################
# COMMON parameters for datasets: END
######################################

# dataset: 'Lung Single-cell RNA-Seq Cell Types'  
# filepath: './datasets/Data_Bischoff2021_Lung_annotated_with_cell_types.parquet'

# dataset: "breast_cancer_wisconsin_diagnostic"
# filepath: "./datasets/breast_cancer_wisconsin_diagnostic.csv"

# dataset: "Colorectal_GSE21510"  
# filepath: "./datasets/Colorectal_GSE21510.csv"

# dataset: "Liver_GSE14520_U133A"
# filepath: "./datasets/Liver_GSE14520_U133A.csv"

# dataset: "GSE4115"
# filepath: './datasets/GSE4115.csv'

# dataset: "ALL_AML"
# filepath: "./datasets/golub_all_aml.csv"

# dataset: "TCGA"
# filepath: "./datasets/tcga_final.parquet"

# dataset: "TCGA_LUAD_LUSC"
# filepath: "./datasets/TCGA_LUAD_LUSC_lung_only_data.csv"

# dataset: "Lung_GSE18842"
# filepath: "./datasets/Lung_GSE18842.csv"

# test_dataset: "Lung_GSE19804"
# test_filepath: "./datasets/Lung_GSE19804.csv"

# dataset: "Lung_GSE19804"
# filepath: "./datasets/Lung_GSE19804.csv"

# test_dataset: "Lung_GSE18842"
# test_filepath: "./datasets/Lung_GSE18842.csv"

# dataset: "Gisette"
# filepath: "./datasets/gisette/GISETTE/gisette_train.data"

# test_dataset: "Gisette_validation"
# test_filepath: "datasets/gisette/GISETTE/gisette_valid.data"


# Links to datasets that were previously downloaded:
  # - https://sbcb.inf.ufrgs.br/data/cumida/Genes/Lung/GSE18842/Lung_GSE18842.csv
  # - https://sbcb.inf.ufrgs.br/data/cumida/Genes/Lung/GSE19804/Lung_GSE19804.csv 
  # - https://archive.ics.uci.edu/static/public/170/gisette.zip
  # - https://sbcb.inf.ufrgs.br/data/cumida/Genes/Liver/GSE14520_U133A/Liver_GSE14520_U133A.csv
  # - https://sbcb.inf.ufrgs.br/data/cumida/Genes/Leukemia/GSE28497/Leukemia_GSE28497.csv
  # - https://sbcb.inf.ufrgs.br/data/cumida/Genes/Colorectal/GSE44076/Colorectal_GSE44076.csv
  # - https://sbcb.inf.ufrgs.br/data/cumida/Genes/Liver/GSE76427/Liver_GSE76427.csv
  # - https://sbcb.inf.ufrgs.br/data/cumida/Genes/Breast/GSE45827/Breast_GSE45827.csv
  # - https://sbcb.inf.ufrgs.br/data/cumida/Genes/Colorectal/GSE21510/Colorectal_GSE21510.csv